### ISSUE TITLE
Add more meta tag, because nowadays is 9999

### ISSUE THREAD

**Issue by Sparta16** [Zerotiger/Infinity-Item-Editor#2]
Max map, for example, is 65,536. Max meta tag in IIE is 9999. Need to increase the number of meta tags for IIE

**Comment by Zerotiger** [comment]
Thanks for reporting the issue. I am planning to do a complete rewrite, so I am not sure if the current IIE will be updated, but I will keep this in mind. It's worth considering though, that meta data doesn't exist in 1.13 anymore.

**Comment by Sparta16** [comment]
Thanks for answer!
